### ISSUE TITLE
Decide application language

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#1]
Make a short write up about why we choose the language we are using

**Comment by Turboen** [comment]
https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_02/README_TASKS.md#3-describe-distributed-workflow

Further described during first section

**Comment by Thomsen96** [comment]
https://medium.com/hackernoon/go-vs-net-core-in-terms-of-http-performance-7535a61b67b8

Most of the group members know, Java, C# and Python

But also wanted to learn Go and from the information that we could find, was Go a faster backend application. So the group decided to look into different frameworks. to get a feel of how they are different and their pros and cons.

**Comment by Lucki2g** [comment]
We choose to refractor the python flask web application to a Go web application. We all have developed web applications in Java, C# and Python previously, however want to try to develop one in Go. Main reason being this should be the "perfect web application language", that Google developed for their own web applications, since Java, C and Python were not good enough for them. From some quick research we found benchmarks that proved the effectiveness of Go compared to the older .Net core 5 (https://medium.com/hackernoon/go-vs-net-core-in-terms-of-http-performance-7535a61b67b8). We were unable to find any newer benchmarks from .Net core 6, however from their documentation on their performance improvements (https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#networking), the changes are not enourmous, and we assume Go has improved as well.
