### ISSUE TITLE
Decide on visualization app

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#100]
Grafana, datadog, nagios, etc

**Comment by Turboen** [comment]
Decided grafana, but needs to elaborate more before closing.

**Comment by Zavir** [comment]
See https://github.com/DevelOpsITU/MiniTwit/issues/99#issuecomment-1068085003

The reasoning for picking Grafana is basically the same as with Prometheus.

**Comment by Turboen** [comment]
As we had chosen Prometheus as our monitoring tool, we wanted to support the information from Prometheus and visualize it in a better way. 

When looking into visualization tools we had several options. Some of these tools include but are not limited to Grafana, Datadog, and Nagios. All of the tools looked to be viable options. However, some were better than others. 

Grafana was quickly our go-to option due to several reasons. 
Firstly some of our team members had prior experience with working with Grafana along with the data collected from Prometheus. This gave us some knowledge of how to set it up and some of its capabilities. 
Additionally, it is a free visualization tool, which in comparison to e.g. Datadog is a big plus. 

Besides Grafana being compatible with Prometheus, it also works well with the logging tool Loki, which we use for logging in our system.
