### ISSUE TITLE
Send monitoring information to Helge

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#106]
- [x] Add pull request to repo
- [x] Add user that helge have requested

**Infomration from the lecture notes:**
Add a link to your monitoring dashboard via a pull request to the file [misc_urls.py](https://github.com/itu-devops/lecture_notes/blob/master/misc_urls.py) in https://github.com/itu-devops/lecture_notes. (Replace the URL "http(s)://<TBA>/" below the comment # Monitoring URL: with your respective URL. Link either a read-only dashboard or add a user with name and credentials that Helge provides you via the Teams chat channel, so that we can see what you are monitoring and can provide feedback on it in the start of the next session.

**Comment by Turboen** [comment]
Add a link to your monitoring dashboard via a pull request to the file [misc_urls.py](https://github.com/itu-devops/lecture_notes/blob/master/misc_urls.py) in https://github.com/itu-devops/lecture_notes. (Replace the URL "http(s)://<TBA>/" below the comment # Monitoring URL: with your respective URL. Link either a read-only dashboard or add a user with name and credentials that Helge provides you via the Teams chat channel, so that we can see what you are monitoring and can provide feedback on it in the start of the next session.

**Comment by Thomsen96** [comment]
Pull request sent

https://github.com/itu-devops/lecture_notes/pull/228

**Comment by Thomsen96** [comment]
I have created  the user and given it "view" rights
