### ISSUE TITLE
Investigate simulator errors on Unfollow and Tweet

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#161]
From viewing and scraping the simulator status, we have seen that we have a continuous error with unfollow and tweet. We should investigate what causes theses errors and fix them in other separate issues. 

Unfollow:
![billede](https://user-images.githubusercontent.com/32035863/160612744-5a321ee1-3847-4ccb-8b27-dcd343624f1b.png)

Tweet:
![billede](https://user-images.githubusercontent.com/32035863/160612786-d2f8881f-a894-4062-b22b-cfb74c1f0436.png)

**Comment by Turboen** [comment]
To query and only show the log messages with error 400 and on endpoint /sim/fllws/:username
- {app="/minitwit"} | json | code="400" | path=~"/sim/fllws/.*"

**Comment by Turboen** [comment]
@Thomsen96 I do not have access to ssh on our servers, which i might need for digging down further into logs. Could you help me with this as soon as possible?

**Comment by Turboen** [comment]
![image](https://user-images.githubusercontent.com/61050781/161405401-fe047a25-beb2-4686-bef5-b57ca94b2342.png)

I suspect this is causing the error. 
If one of the two users does not exist, we create them using our "hack". However, no matter if we use the hack or not, we still call unfollow on the database.
This should be changed, such that nothing will happen after users have been created (since unfollow, just means their original state as new users.

**Comment by Turboen** [comment]
### Tweet

![image](https://user-images.githubusercontent.com/61050781/161437129-4230113c-4802-48da-91d3-1913d31f9bff.png)
When we got the error the returned error message should be : "Could not add  the message". This could be used to query the logs

To find what causes error in tweet we first ran the query: 
{app="/minitwit"} | json | level="error" | message="Could not add the message"

![image](https://user-images.githubusercontent.com/61050781/161437215-251b2c87-9dbd-44e5-a185-b5b025fc355a.png)
From this we could see that the error was "user not found". Therefore it probably had something to do with the same problem as follow/unfollow user missing.


{app="/minitwit"} | json | level="warn" | path=~"/sim/msgs/Martine Borski"
