### ISSUE TITLE
Decide which Framework to use

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#33]
Make a short write up of what why and what framework we choose to use

**Comment by Zavir** [comment]
Initially, we discussed the suggested frameworks and programming languages proposed in the second exercise session:

- [Go](http://golang.org/) with [Gorilla](http://www.gorillatoolkit.org/)
- [Crystal](https://crystal-lang.org/) with [Kemal](https://kemalcr.com/)
- [Elixir](https://elixir-lang.org/) with [Phoenix](https://www.phoenixframework.org/)
- [Nim](https://nim-lang.org/) with [Jester](https://github.com/dom96/jester)
- [Ruby](https://www.ruby-lang.org/) with [Sinatra](http://sinatrarb.com/)

The main motivation was the desire to learn **something new**. Thus, the above suggestions were quite good, since we could exclude ordinary and well known languages, such as Java, C#, Python, etc.  In the end, we went with the Go programming language. See #1 for more information regarding this.

In regard to the framework, we discussed multiple different options including **Gorilla**.  We researched other frameworks by simply searching for suggested Go web frameworks and then discussing pros and cons in regard to these. Other than **Gorilla**, we found the following to be of some interest:

- [Gin](https://github.com/gin-gonic/gin)
- [Iris](https://github.com/kataras/iris)
- [Echo](https://echo.labstack.com/)

After narrowing down our options to the above frameworks (and Gorilla), we decide to open two different branches where we could try out two different frameworks. We choose **Gorilla**, since it was recommended by the lecturer, and Gin since it had the most publicity on GitHub (most stars, forks, etc). After working a few days with Gorilla and Gin, we decided to discontinue the Gorilla branch, since Gin had more documentation and was overall easier to use. Furthermore, we also learnt that Gin and Gorilla have the same functionality, which is probably the case with these types of frameworks.

**Comment by Zavir** [comment]
@Lucki2g kom hid.
