### ISSUE TITLE
Decide on CI/CD system

### ISSUE THREAD

**Issue by ValarMarkhulis** [DevelOpsITU/MiniTwit#58]
As MSc students we should investigate and analyse the different CI/CD systems that are offered by different companies.

**Comment by Zavir** [comment]
Initially we had to choose between **self-hosted options** and **CI/CD as a service**. Some of these options include:

Self-hosted: 
- Jenkins
- Bamboo
- Azure DevOps Server

CI/CD as a service:
- Travis CI
- CircleCI
- Github Actions

The self-hosted option is usually nice when you're dealing with a deployment system that does scale linearly. Thus, this is usually a much cheaper option for huge companies like Amazon, Facebook, Google, etc, since they already have the necessary facilities and developers to make this run smoothly. On the other hand, a service is nice when you don't have the facilities or manpower. This is the case for MiniTwit and thus we decided to go with a service. 

When deciding which service to run with, we took the same approach as when choosing framework/programming language. We red online articles and choose the one that was most supported and well documented. Furthermore, it was also important we didn't have the deployment system on the same platform as the codebase, which is why we didn't go with GitHub Actions (even though it was free). In the end we settled on Travis CI, since it is an extremely popular service that is widely used in the industry. Furthermore, it was easier to go with this option, since it was well documented how to use it in the exercises for session 4.

**Comment by Lucki2g** [comment]
True
Fight Bugs                      |     |
                                \\_V_//
                                \/=|=\/
                                 [=v=]
                               __\___/_____
                              /..[  _____  ]
                             /_  [ [  M /] ]
                            /../.[ [ M /@] ]
                           <-->[_[ [M /@/] ]
                          /../ [.[ [ /@/ ] ]
     _________________]\ /__/  [_[ [/@/ C] ]
    <_________________>>0---]  [=\ \@/ C / /
       ___      ___   ]/000o   /__\ \ C / /
          \    /              /....\ \_/ /
       ....\||/....           [___/=\___/
      .    .  .    .          [...] [...]
     .      ..      .         [___/ \___]
     .    0 .. 0    .         <---> <--->
  /\/\.    .  .    ./\/\      [..]   [..]
 / / / .../|  |\... \ \ \    _[__]   [__]_
/ / /       \/       \ \ \  [____>   <____]
