### ISSUE TITLE
Migrate data from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#92]
Now that the MiniTwit application is running on the server are we currently appending data to the SQLite database saved on the application server. 

With the work in #37 and #89 should it have become easier to move the database from SQLite to PostgreSQL. 

But we still need to test the use of PostgreSQL server with the use of GORM. 

Next do we need to make a plan for how to migrate the data from the Application server to the Database server. with as little impact/down time as possible. In order to achieve this goal we can make some local tests and scripts that executes this.

1. Create a new SQLite database
2. Run simulator on the MiniTwit application (Simulates the current situation of the live database)
3. Create a new localhost Postgre database
4. Execute a migration plan to test the performance and how it works. 
   - Can we migrate the data while the application is running?
   - Make estimates of the downtime impact? (Not really important, but could be fun to make)
5. Move MiniTwit application to use the postgre server. Must be very easy, if not automatic 

- [x] Test the application against a local postgre database 
- [x] Find data migration plan
- [x] Make a complete or couple of scripts that executes the different steps.

**Comment by Thomsen96** [comment]
Tools that could be useful for the operation that we are going to do:
- https://github.com/dimitri/pgloader

**Comment by Lucki2g** [comment]
Changing to postgresql needs some refactoring. I will keep a list of what changes are made and why:
- [x]  timeline sql queries (postgres needs the joined table to be in 
     - [x] public
     - [x] personal
     - [x] user
- [x] salt creation (postgres does not like out way of creating hashes (not utf-8))
- [ ]

**Comment by Thomsen96** [comment]
@Lucki2g  Regarding the salt creation could you expand on what the challenge is and how exactly how it have been mitigated?

**Comment by Lucki2g** [comment]
> @Lucki2g Regarding the salt creation could you expand on what the challenge is and how exactly how it have been mitigated?

The struggle started with translation from python to go. The way the salt is saved in the py application, is using an outdated library (werzinking or something like that), using sha-1 for hashing. Anyways the salts are made of 8 characters no symbols, just [a-zA-Z0-9]. In go we wanted to make a random byte slice (array) and transform it into a string. However, the random byte array contains mostly non existing UTF-8 characters. We found a work around for SQLite where the salt would be saved as a BLOB entity. Now with postgre, we no longer support these weird characters, so basically to only change code in one file the salt is now randomly generated like the old school outdated library.

I'm actually afraid that the salts made for SQLite may break postgre... or not work... this is really bad now that I think about it. **SHIT**

In reality I would have liked to separate salt from hash and changed the user table. Furthermore, made the salt be made by a newer crypto library for go, but we thought initially that the seed data needed to be in the new application, so we had to have identical salting format (turned out it didn't **SHIT** once again)
